[package]
name = "ear-training"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-music-theory = { git = "https://github.com/ozankasikci/rust-music-theory.git" }
rodio = "0.20.1"
rand = "0.9.0"
lazy_static = "1.5.0"
regex = "1.11.1"